version: '3.3'

services:
 apache:
    build: ./php
    ports:
      - "80:80"
    volumes:
      - ./php:/usr/local/apache2/htdocs/
    depends_on:
      - php
    container_name: apache
 
 php:
    image: php:7.4-fpm
    volumes:
      - ./php:/usr/local/apache2/htdocs/
    ports:
      - "9000:9000"
    container_name: php 
 
 db:
  container_name: mysql8
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: test
   MYSQL_USER: admin
   MYSQL_PASSWORD: root
  volumes:
        - ./mysql-data:/var/lib/mysql
  ports:
   - 3306:3306
 phpmya:
  image: phpmyadmin/phpmyadmin:latest
  container_name: phpmyadmin
  environment:
     MYSQL_USERNAME: root
     MYSQL_ROOT_PASSWORD: root  
  ports:
   - 8899:80
  depends_on:
   - db